<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit548771db78361ecd1cb05c448dd16f7d
{
    public static $prefixLengthsPsr4 = array (
        'w' => 
        array (
            'wordpressBook\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'wordpressBook\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit548771db78361ecd1cb05c448dd16f7d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit548771db78361ecd1cb05c448dd16f7d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit548771db78361ecd1cb05c448dd16f7d::$classMap;

        }, null, ClassLoader::class);
    }
}
